language: java
sudo: true
dist: trusty
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "tillias-github"

    token:
      secure: $SONAR_TOKEN

cache:
  directories:
  - $HOME/.m2

before_install:
- chmod +x mvnw
script:
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar