language: java
sudo: true
dist: trusty
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "tillias-github"

    token:
      secure: $SONAR_TOKEN

before_install:
- chmod +x mvnw
script:
- ./mvnw clean install sonar:sonar